name: pr-title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate semantic PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          subjectPattern: "^(.*) AB#[0-9]+$"
          subjectPatternError: |
            The subject: "{subject}" in the pull request with title: "{title}" does not match the required pattern.
            Please ensure the title ends with "AB#<HU-ID>", where <HU-ID> is the Azure DevOps work item ID related to this change.
